name: pharmvip-guideline
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - argh=0.26.2
  - attrs=20.3.0
  - autopep8=1.5.4
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2020.10.14
  - certifi=2020.11.8
  - click=7.1.2
  - colorama=0.4.4
  - coloredlogs=14.0
  - curl=7.71.1
  - cyvcf2=0.11.7
  - docopt=0.6.2
  - htslib=1.9
  - humanfriendly=8.2
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - iniconfig=1.1.1
  - intel-openmp=2019.4
  - krb5=1.18.2
  - libcurl=7.71.1
  - libcxx=10.0.0
  - libdeflate=1.0
  - libedit=3.1.20191231
  - libffi=3.2.1
  - libssh2=1.9.0
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - more-itertools=8.6.0
  - ncurses=6.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - openssl=1.1.1h
  - packaging=20.4
  - pandas=1.1.3
  - pathtools=0.1.2
  - pip=20.2.4
  - pluggy=0.13.1
  - py=1.9.0
  - pycodestyle=2.6.0
  - pyparsing=2.4.7
  - pytest=6.1.2
  - pytest-watch=4.1.0
  - python=3.7.6
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2020.1
  - pyyaml=5.3.1
  - readline=7.0
  - setuptools=50.3.1
  - six=1.15.0
  - sqlite=3.33.0
  - tk=8.6.10
  - toml=0.10.2
  - watchdog=0.10.3
  - wheel=0.35.1
  - xlrd=1.2.0
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.4.0
  - zlib=1.2.11
