name: pharmvip-guideline
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python=3.9.5
  - pip=21.2.4
  - pandas=1.3.5
  - cyvcf2=0.30.14
  - xlsxwriter=3.0.2
  - pip:
    -  -e .